FROM node:20-alpine

WORKDIR /app

COPY services/auth/package.json ./services/auth/package.json
RUN npm --prefix services/auth install

COPY services/auth ./services/auth

EXPOSE 4001

CMD ["node","services/auth/index.js"]

