FROM node:20-alpine

WORKDIR /app

COPY services/notifications/package.json ./services/notifications/package.json
RUN npm --prefix services/notifications install

COPY services/notifications ./services/notifications

EXPOSE 4005

CMD ["node","services/notifications/index.js"]

