FROM node:20-alpine

WORKDIR /app

COPY services/traffic/package.json ./services/traffic/package.json
RUN npm --prefix services/traffic install

COPY services/traffic ./services/traffic

EXPOSE 4003

CMD ["node","services/traffic/index.js"]

